runtime: custom
env: flex

network:
  forwarded_ports:
    - 80:8080

env_variables:
  API_URL: $APP_SECRET_API_URL
  PLAYLIS_GUARD_WEBSITE_URL: $APP_SECRET_PLAYLIS_GUARD_WEBSITE_URL
  ADMIN_KEY: $APP_SECRET_ADMIN_KEY
  ENCRYPTION_PASSWORD: $APP_SECRET_ENCRYPTION_PASSWORD
  JWT_SECRET: $APP_SECRET_JWT_SECRET
  JWT_EXPIRES_IN: $APP_SECRET_JWT_EXPIRES_IN
  DATABASE_URL: $APP_SECRET_DATABASE_URL
  SPOTIFY_CLIENT_ID: $APP_SECRET_SPOTIFY_CLIENT_ID
  SPOTIFY_CLIENT_SECRET: $APP_SECRET_SPOTIFY_CLIENT_SECRET
  CALLBACK_URL: $APP_SECRET_CALLBACK_URL




