version: '3.1'

services:
  main:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - './.docker/postgres/data:/var/lib/postgresql/data'
