name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npm run lint

      - name: Setting Github user.email
        run: git config --global user.email "<65380139+marcus-castanho@users.noreply.github.com>"

      - name: Setting Github user.name
        run: git config --global user.name "<Marcus>"

      - name: Adding fixes for committing
        run: git add .

      - name: Committing ESLint fixes
        run: git commit -m "fixed ESLint issues"

      - name: Pushing fixes to current PR branch
        run: git push
