name: CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and deploy app on Render
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: echo "Auto deploy enabled on Render. Verify the deploying pipeline in the events tab in the Render app page."
