name: CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and deploy app on Render
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: echo "Deploying to Render"
